import type { ValidatedLead } from "./lead-schema.js";

/**
 * Renders the confirmation email sent to a lead after they submit the
 * contact form. The email is built here (code-controlled, versioned in
 * git) instead of being generated by the n8n AI agent, so the design
 * stays consistent and editable through PRs.
 *
 * Design notes:
 * - Tables + inline CSS — required for email clients (Gmail strips <style>).
 * - 600px max width — standard for mail.
 * - Brand colors taken from src/index.css (--primary teal, --background deep).
 * - System font stack for fast render; fallback to Heebo for Hebrew.
 * - dir="rtl" on the <html> for Hebrew so the layout flips correctly.
 */

interface EmailContent {
  subject: string;
  preheader: string;
  greeting: string;
  intro: string;
  confirmation: string;
  nextSteps: string;
  ctaLabel: string;
  footerTagline: string;
  signOff: string;
  signature: string;
}

const COPY: Record<ValidatedLead["language"], EmailContent> = {
  fr: {
    subject: "Zyflows — votre demande a bien été reçue",
    preheader: "Merci pour votre message. On revient vers vous sous 24h ouvrées.",
    greeting: "Bonjour",
    intro:
      "Merci d'avoir pris contact avec Zyflows. Votre demande a bien été reçue et est désormais entre nos mains.",
    confirmation:
      "Nous étudions votre besoin et reviendrons vers vous personnellement sous 24 heures ouvrées avec une première réponse et, si pertinent, un créneau pour un audit gratuit.",
    nextSteps:
      "En attendant, n'hésitez pas à parcourir nos services pour vous donner une idée de ce que nous savons faire.",
    ctaLabel: "Découvrir nos services",
    footerTagline: "Automatisation • Agents IA • Chatbots • CRM • Israël",
    signOff: "À très vite,",
    signature: "L'équipe Zyflows",
  },
  en: {
    subject: "Zyflows — we received your request",
    preheader: "Thanks for reaching out. We'll get back to you within 24 business hours.",
    greeting: "Hi",
    intro:
      "Thanks for reaching out to Zyflows. Your request landed safely and is now in our hands.",
    confirmation:
      "We're reviewing your needs and will get back to you personally within 24 business hours with a first response and, if relevant, a slot for a free audit.",
    nextSteps:
      "In the meantime, feel free to browse our services to get a sense of what we can do.",
    ctaLabel: "Explore our services",
    footerTagline: "Automation • AI Agents • Chatbots • CRM • Israel",
    signOff: "Talk soon,",
    signature: "The Zyflows team",
  },
  he: {
    subject: "Zyflows — קיבלנו את פנייתך",
    preheader: "תודה על הפנייה. נחזור אליך תוך 24 שעות עסקים.",
    greeting: "שלום",
    intro:
      "תודה שפנית ל-Zyflows. הפנייה שלך התקבלה אצלנו והיא כבר בידיים שלנו.",
    confirmation:
      "אנחנו לומדים את הצורך שלך ונחזור אליך באופן אישי תוך 24 שעות עסקים עם תשובה ראשונה, ואם רלוונטי — זמן לשיחת אודיט חינם.",
    nextSteps:
      "בינתיים, אתה מוזמן לעיין בשירותים שלנו כדי להבין מה אנחנו יודעים לעשות.",
    ctaLabel: "לשירותים שלנו",
    footerTagline: "אוטומציה • סוכני AI • צ'אטבוטים • CRM • ישראל",
    signOff: "להתראות בקרוב,",
    signature: "צוות Zyflows",
  },
};

const escape = (s: string): string =>
  s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const firstName = (fullName: string): string => fullName.trim().split(/\s+/)[0] ?? "";

const SERVICES_URL = "https://www.zyflows.com";

export interface RenderedLeadEmail {
  subject: string;
  html: string;
}

export function renderLeadEmail(lead: ValidatedLead): RenderedLeadEmail {
  const c = COPY[lead.language];
  const dir = lead.language === "he" ? "rtl" : "ltr";
  const lang = lead.language;
  const localizedHomeUrl = `${SERVICES_URL}/${lang}/services`;
  const first = escape(firstName(lead.name));

  // System font stack with Heebo as Hebrew fallback. No external <link>
  // because most email clients block external CSS anyway.
  const fontStack =
    lang === "he"
      ? "'Heebo', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
      : "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

  const html = `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escape(c.subject)}</title>
</head>
<body style="margin:0;padding:0;background:#0a1518;font-family:${fontStack};">
  <!-- preheader (hidden, shows in inbox preview) -->
  <div style="display:none;font-size:1px;color:#0a1518;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
    ${escape(c.preheader)}
  </div>

  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#0a1518;">
    <tr>
      <td align="center" style="padding:32px 16px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:600px;background:#0f1f23;border-radius:20px;overflow:hidden;box-shadow:0 8px 32px rgba(0,0,0,0.3);">

          <!-- HEADER -->
          <tr>
            <td style="background:linear-gradient(135deg,#0d2025 0%,#164048 100%);padding:40px 32px;text-align:center;">
              <div style="display:inline-block;width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,#22d3ee 0%,#0e9888 100%);line-height:56px;text-align:center;color:#0a1518;font-weight:800;font-size:28px;font-family:${fontStack};">Z</div>
              <div style="margin-top:14px;color:#e6fbff;font-size:24px;font-weight:700;letter-spacing:-0.5px;">Zyflows</div>
            </td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="padding:40px 36px;color:#dff7fb;font-size:16px;line-height:1.7;">
              <p style="margin:0 0 24px;font-size:18px;color:#ffffff;">
                ${escape(c.greeting)} <strong>${first || escape(lead.name)}</strong>,
              </p>

              <p style="margin:0 0 20px;color:#bfe6ee;">
                ${escape(c.intro)}
              </p>

              <div style="margin:28px 0;padding:20px 22px;background:rgba(34,211,238,0.08);border-${dir === "rtl" ? "right" : "left"}:3px solid #22d3ee;border-radius:8px;">
                <p style="margin:0;color:#e6fbff;">
                  ${escape(c.confirmation)}
                </p>
              </div>

              <p style="margin:0 0 28px;color:#bfe6ee;">
                ${escape(c.nextSteps)}
              </p>

              <!-- CTA -->
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto;">
                <tr>
                  <td style="border-radius:12px;background:linear-gradient(135deg,#22d3ee 0%,#0e9888 100%);">
                    <a href="${localizedHomeUrl}" style="display:inline-block;padding:14px 32px;color:#0a1518;text-decoration:none;font-weight:700;font-size:15px;border-radius:12px;">
                      ${escape(c.ctaLabel)} →
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Sign-off -->
              <p style="margin:40px 0 4px;color:#bfe6ee;">
                ${escape(c.signOff)}
              </p>
              <p style="margin:0;color:#ffffff;font-weight:600;">
                ${escape(c.signature)}
              </p>
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="background:#0a1518;padding:24px 32px;text-align:center;border-top:1px solid #1d3a40;">
              <p style="margin:0 0 6px;color:#7aa5ad;font-size:12px;letter-spacing:0.3px;">
                ${escape(c.footerTagline)}
              </p>
              <p style="margin:0;font-size:12px;">
                <a href="https://www.zyflows.com" style="color:#22d3ee;text-decoration:none;">www.zyflows.com</a>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  return { subject: c.subject, html };
}
