import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';

// Language types and context for internationalization
export type Language = 'he' | 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

// Update document direction and language class when language changes
const updateDocumentDirection = (lang: Language) => {
  const dir = lang === 'he' ? 'rtl' : 'ltr';
  document.documentElement.setAttribute('dir', dir);
  document.documentElement.setAttribute('lang', lang);

  // Remove all language classes and add current one
  document.body.classList.remove('lang-he', 'lang-fr', 'lang-en');
  document.body.classList.add(`lang-${lang}`);
};

const translations: Record<Language, Record<string, string>> = {
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.about': 'אודות',
    'nav.services': 'שירותים',
    'nav.pricing': 'חבילות',
    'nav.contact': 'צור קשר',
    'nav.cta': 'קבלו ייעוץ חינם',

    // Hero Section
    'hero.badge': '🚀 הדור הבא של האוטומציה העסקית',
    'hero.title1': 'הפכו את העסק שלכם עם',
    'hero.title2': 'אוטומציה חכמה',
    'hero.subtitle': 'תפסיקו לבזבז זמן. אנחנו בונים מערכות שעובדות 24/7, מייעלות תהליכים, ומגדילות את הרווחים שלכם.',
    'hero.cta1': 'קבלו אבחון חינם',
    'hero.cta2': 'גלו את השירותים שלנו',

    // SEO
    'meta.home.title': 'Zyflows | פתרונות אוטומציה ו-AI',
    'meta.home.description': 'סוכנות לאוטומציה עסקית בינה מלאכותית. אנו בונים מערכות חכמות לייעול תהליכים, חיסכון בזמן והגדלת רווחים.',
    'meta.about.title': 'אודות Zyflows | המומחים לאוטומציה',
    'meta.about.description': 'הכירו את Zyflows ואת המייסד רפאל. מומחים באוטומציה עסקית ופיתוח פתרונות דיגיטליים חכמים.',
    'meta.services.title': 'השירותים שלנו | Zyflows',
    'meta.services.description': 'אוטומציה, צ\'אטבוטים, פתרונות ווב ועוד. גלו איך אנחנו יכולים לשדרג את העסק שלכם.',
    'meta.contact.title': 'צור קשר | Zyflows',
    'meta.contact.description': 'מוכנים להתקדם? צרו איתנו קשר לייעוץ בנושאי אוטומציה ופיתוח עסקי.',
    'meta.pricing.title': 'חבילות מחירים | Zyflows',
    'meta.pricing.description': 'חבילות תמיכה ותחזוקה לעסקים. בחרו את החבילה המתאימה לצרכים שלכם.',
    'meta.terms.title': 'תנאי שימוש | Zyflows',
    'meta.terms.description': 'תנאי השימוש של Zyflows. קראו את המדיניות שלנו לפני השימוש בשירותינו.',
    'meta.privacy.title': 'מדיניות פרטיות | Zyflows',
    'meta.privacy.description': 'מדיניות הפרטיות של Zyflows. אנו מחויבים להגנה על המידע האישי שלכם.',
    'meta.accessibility.title': 'הצהרת נגישות | Zyflows',
    'meta.accessibility.description': 'Zyflows מחויבת לנגישות דיגיטלית מלאה עבור כל המשתמשים.',

    // Services Section (Index)
    'services.title': 'פתרונות לצמיחה עסקית',
    'services.subtitle': 'אנחנו מציעים מגוון שירותים שיעזרו לעסק שלכם לצמוח ולהתייעל',
    'services.learnMore': 'למידע נוסף',
    'services.diagnosis.title': 'אבחון עסקי',
    'services.diagnosis.desc': 'נזהה את הנקודות הכי קריטיות לשיפור ואוטומציה בעסק שלכם.',
    'services.automation.title': 'אוטומציה',
    'services.automation.desc': 'נבנה מערכות שעובדות 24/7 ומחליפות עבודה ידנית.',
    'services.chatbots.title': 'צ\'אטבוטים',
    'services.chatbots.desc': 'בוטים חכמים שמטפלים בלקוחות ומגדילים מכירות.',
    'services.web.title': 'פתרונות ווב',
    'services.web.desc': 'אתרים ומערכות ווב מתקדמות לעסק שלכם.',

    // Process Section
    'process.title': 'איך זה עובד?',
    'process.subtitle': 'תהליך פשוט ויעיל שמוביל לתוצאות מדהימות',
    'process.step1.title': 'אבחון',
    'process.step1.desc': 'מנתחים את התהליכים הקיימים ומזהים הזדמנויות לשיפור.',
    'process.step2.title': 'בנייה',
    'process.step2.desc': 'מפתחים ומטמיעים פתרונות אוטומציה מותאמים אישית.',
    'process.step3.title': 'צמיחה',
    'process.step3.desc': 'מרחיבים ומשפרים בהתאם לצרכים המתפתחים של העסק.',

    // Pricing Section
    'pricing.title': 'חבילות תמיכה ותחזוקה',
    'pricing.subtitle': 'בחרו את החבילה שמתאימה לצרכים שלכם',
    'pricing.recommended': 'מומלץ',
    'pricing.mostPopular': 'הכי פופולרי',
    'pricing.contactUs': 'צור קשר',
    'pricing.essential.desc': 'לעסקים קטנים שרוצים להתחיל',
    'pricing.business.desc': 'לעסקים בצמיחה שצריכים יותר',
    'pricing.vip.desc': 'לעסקים שדורשים את המקסימום',
    'pricing.feature.support2h': 'שעתיים תמיכה בחודש',
    'pricing.feature.support6h': '6 שעות תמיכה בחודש',
    'pricing.feature.support15h': '15 שעות תמיכה בחודש',
    'pricing.feature.basicMaintenance': 'תחזוקה בסיסית',
    'pricing.feature.advancedMaintenance': 'תחזוקה מתקדמת',
    'pricing.feature.fullMaintenance': 'תחזוקה מלאה',
    'pricing.feature.monthlyReport': 'דוח חודשי',
    'pricing.feature.weeklyReports': 'דוחות שבועיים',
    'pricing.feature.dailyReports': 'דוחות יומיים',
    'pricing.feature.response48h': 'זמן תגובה: 48 שעות',
    'pricing.feature.response24h': 'זמן תגובה: 24 שעות',
    'pricing.feature.response4h': 'זמן תגובה: 4 שעות',
    'pricing.feature.monthlyOptimization': 'אופטימיזציה חודשית',
    'pricing.feature.premiumTools': 'גישה לכלים פרימיום',
    'pricing.feature.dedicatedManager': 'מנהל לקוח ייעודי',
    'pricing.feature.customDev': 'פיתוחים מותאמים',
    'pricing.feature.personalTraining': 'הדרכות אישיות',

    // Contact Section
    'contact.title': 'בואו נדבר',
    'contact.subtitle': 'יש לכם שאלות? רוצים לדעת איך אנחנו יכולים לעזור לעסק שלכם? השאירו פרטים ונחזור אליכם תוך 24 שעות.',
    'contact.whatsappDesc': 'תגובה מהירה תוך דקות',
    'contact.whatsappBtn': 'דברו איתנו בוואטסאפ',
    'contact.form.name': 'שם מלא',
    'contact.form.namePlaceholder': 'הכניסו את שמכם',
    'contact.form.phone': 'טלפון',
    'contact.form.phonePlaceholder': '050-000-0000',
    'contact.form.email': 'אימייל',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.message': 'הודעה',
    'contact.form.messagePlaceholder': 'ספרו לנו על העסק שלכם ואיך נוכל לעזור...',
    'contact.form.submit': 'שלחו הודעה',
    'contact.form.businessName': 'שם העסק',
    'contact.form.businessPlaceholder': 'שם החברה או העסק שלכם',
    'contact.form.subject': 'במה נוכל לעזור?',
    'contact.form.selectTopic': 'בחרו נושא',
    'contact.form.topicDiagnosis': 'אבחון עסקי',
    'contact.form.topicAutomation': 'אוטומציה',
    'contact.form.topicChatbot': 'צ\'אטבוט',
    'contact.form.topicWeb': 'פתרונות ווב',
    'contact.form.topicSupport': 'חבילות תמיכה',
    'contact.form.topicOther': 'אחר',
    'contact.form.responseTime': 'נחזור אליכם תוך 24 שעות עסקים',
    'contact.form.sendRequest': 'שלחו פנייה',

    // Contact Info
    'contact.email': 'אימייל',
    'contact.phone': 'טלפון',
    'contact.phoneIsrael': 'ישראל',
    'contact.phoneFrance': 'צרפת',
    'contact.offices': 'משרדים',
    'contact.hours': 'שעות פעילות',
    'contact.hoursValue': 'א\'-ה\' 09:00-18:00',
    'contact.location': 'תל אביב, ישראל',
    'contact.whatsappTitle': 'מעדיפים וואטסאפ?',
    'contact.whatsappQuick': 'קבלו מענה מהיר תוך דקות',
    'contact.whatsappSend': 'שלחו הודעה בוואטסאפ',
    'contact.talkToUs': 'דברו איתנו בוואטסאפ',
    'contact.ways': 'דרכי התקשרות',
    'contact.leaveDetails': 'השאירו פרטים',
    'contact.heroTitle': 'בואו',
    'contact.heroTitle2': 'נדבר',
    'contact.heroSubtitle': 'יש לכם שאלות? רוצים לדעת איך אנחנו יכולים לעזור? אנחנו כאן בשבילכם.',

    // Footer
    'footer.company': 'החברה',
    'footer.services': 'שירותים',
    'footer.contact': 'יצירת קשר',
    'footer.rights': 'כל הזכויות שמורות.',
    'notFound.title': 'העמוד לא נמצא',
    'notFound.description': 'מצטערים, העמוד שחיפשתם לא קיים. אולי הקישור שגוי או שהעמוד הוסר.',
    'notFound.cta': 'חזרה לדף הבית',
    'footer.terms': 'תנאי שימוש',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.accessibility': 'הצהרת נגישות',
    'footer.desc': 'סוכנות אוטומציה מובילה שמתמחה בבניית מערכות חכמות לעסקים. אנחנו עוזרים לכם לחסוך זמן ולהגדיל רווחים.',
    'footer.createdBy': 'אתר זה נוצר על ידי',
    'creator.title': 'יועץ AI ומפתח פתרונות Web Full Stack',
    'creator.bio': 'יועץ בינה מלאכותית ומפתח פתרונות ווב מקצה לקצה. אני עוזר לעסקים לאמץ טכנולוגיות AI ולבנות מערכות דיגיטליות שעובדות.',
    'creator.contact': 'צור קשר',
    'creator.email': 'אימייל',
    'creator.phone': 'טלפון',
    'creator.whatsapp': 'וואטסאפ',
    'creator.linkedin': 'לינקדאין',

    // About Page
    'about.badge': 'אודות Zyflows',
    'about.heroTitle': 'הפיכת תהליכים מורכבים למערכות פשוטות, אוטומטיות ואמינות',
    'about.heroSubtitle': 'Zyflows מלווה עסקים שרוצים להפסיק לבזבז זמן על משימות ידניות, לא מאורגנות או עם כלים לא מתאימים.',
    'about.introTitle': 'הכרות ישירה',
    'about.introText': 'שמי רפאל, מייסד Zyflows. אני יועץ לאוטומציה מבוססת AI ופיתוח פתרונות דיגיטליים לעסקים קטנים ובינוניים, עצמאיים וצוותים תפעוליים. העבודה שלי היא לבנות, לאוטמט ולייעל תהליכים עסקיים עם כלים מודרניים, בלי מורכבות מיותרת.',
    'about.whyTitle': 'למה יצרתי את Zyflows',
    'about.whyProblem': 'ראיתי יותר מדי עסקים משתמשים בכלים חזקים בצורה לא יעילה. תוכנות מוערמות, משימות ידניות חוזרות על עצמן, טעויות אנוש שניתן היה למנוע, ובזבוז זמן מתמיד.',
    'about.whyBackground': 'עם הניסיון שלי מהשטח - צבא, אבטחת מידע, פיתוח ואוטומציה - הבנתי דבר מהותי אחד: מערכת צריכה להיות יציבה, ברורה וניתנת לשליטה, אחרת היא הופכת לבעיה במקום לפתרון.',
    'about.whyConclusion': 'יצרתי את Zyflows כדי להביא את המבנה הזה. לא כדי למכור טכנולוגיה, אלא כדי לספק מערכות שעובדות באמת במציאות העסקית.',
    'about.founderTitle': 'אודות המייסד',
    'about.founderName': 'רפאל',
    'about.founderRole': 'יועץ אוטומציה AI | מייסד Zyflows',
    'about.founderLocation': 'מבוסס בישראל, עובד עם לקוחות בצרפת ובישראל',
    'about.founderLang': 'צרפתית, אנגלית, עברית',
    'about.pathTitle': 'המסלול שלי',
    'about.path1': 'שירות צבאי - תרבות של אחריות, נהלים ועבודה תחת לחץ',
    'about.path2': 'הכשרה באבטחת מידע - הבנה עמוקה של אבטחה, אמינות וניהול סיכונים',
    'about.path3': 'מפתח Full Stack - הבנה של צד הלקוח והלוגיקה מצד השרת',
    'about.path4': 'כרגע בשנה שנייה לתואר ראשון בניהול עסקים ומערכות מידע',
    'about.path5': 'התמחות באוטומציה no-code, סוכני AI ותהליכי עבודה מורכבים',
    'about.deliverTitle': 'מה אני מספק',
    'about.deliver1': 'אוטומציה של תהליכים עסקיים שלמים',
    'about.deliver2': 'ביטול משימות ידניות חוזרות על עצמן',
    'about.deliver3': 'הפחתה דרסטית של טעויות אנוש',
    'about.deliver4': 'חיסכון של 20-40 שעות בחודש לצוותים תפעוליים',
    'about.positionNote': 'אני לא מציב את עצמי כמבצע טכני בלבד. אני עוזר ללקוחות שלי לבנות מבנה לפעילות שלהם, לא רק לחבר כלים.',
    'about.methodTitle': 'הגישה והפילוסופיה שלי',
    'about.methodIntro': 'החזון שלי פשוט: אוטומציה טובה צריכה להיות מובנת, אמינה וניתנת לתחזוקה, גם בלעדיי.',
    'about.method1.title': 'גילוי',
    'about.method1.desc': 'אני מתחיל בהבנת העסק שלך, האילוצים ונקודות החיכוך האמיתיות.',
    'about.method2.title': 'עיצוב',
    'about.method2.desc': 'אני מתכנן ארכיטקטורה לוגית, קריאה וסקלאבילית. בלי פתרונות זמניים עמומים.',
    'about.method3.title': 'יישום',
    'about.method3.desc': 'אני בונה את ה-workflows, סוכני ה-AI או פתרונות הווב, עם בדיקות ותיעוד.',
    'about.method4.title': 'מדידה',
    'about.method4.desc': 'אנחנו מודדים רווחים מוחשיים: זמן, אמינות, ביצועים. ואז מייעלים.',
    'about.methodConclusion': 'מה שמבדיל את Zyflows זו האחריות מקצה לקצה. אני לא מספק תרחישים בודדים. אני מספק מערכות שאפשר להפעיל.',
    'about.servicesTitle': 'שירותים ומומחיות',
    'about.servicesIntro': 'Zyflows מתמקד בעיקר בשלושה צירים.',
    'about.service1.title': 'אוטומציה של תהליכי עבודה',
    'about.service1.desc': 'יצירת תהליכים מתקדמים עם n8n, Make וכלי no-code.',
    'about.service1.result': 'תוצאה טיפוסית: ביטול משימות ידניות וחיסכון מיידי בזמן.',
    'about.service2.title': 'צ\'אטבוטים AI וסוכנים חכמים',
    'about.service2.desc': 'הטמעת סוכנים שמסוגלים לענות, לסנן, לתזמן ולהפעיל פעולות.',
    'about.service2.result': 'תוצאה טיפוסית: תגובתיות טובה יותר ללקוח והפחתת עומס אנושי.',
    'about.service3.title': 'פתרונות ווב מחוברים',
    'about.service3.desc': 'יצירת אתרים וכלי ווב מחוברים למערכות אוטומציה ו-AI.',
    'about.service3.result': 'תוצאה טיפוסית: מסע לקוח חלק ותהליכים מרוכזים.',
    'about.testimonialsTitle': 'מה אומרים הלקוחות',
    'about.testimonial1.text': '"רפאל בנה לנו את התהליכים מא\' עד ת\'. חסכנו המון זמן ובעיקר קיבלנו אמינות."',
    'about.testimonial1.author': 'מנכ"ל, חברת שירותים',
    'about.testimonial2.text': '"מה שעושה את ההבדל זו הבהירות. הכל מוסבר, מתועד ונשלט."',
    'about.testimonial2.author': 'יועץ עצמאי',
    'about.testimonial3.text': '"האוטומציה שהוטמעה באמת עובדת ביום-יום, בלי תלות."',
    'about.testimonial3.author': 'מייסד, סטארטאפ',
    'about.ctaTitle': 'ומה עכשיו?',
    'about.ctaText': 'אם אתה קורא את העמוד הזה, כנראה שאתה יודע שהתהליכים שלך יכולים להיות מאורגנים ואוטומטיים יותר.',
    'about.ctaProposition': 'אני מציע לך דבר פשוט: שיחה כנה, בלי לחץ מכירתי, כדי לראות אם Zyflows רלוונטי בשבילך.',
    'about.ctaButton1': 'קבעו שיחת ייעוץ',
    'about.ctaButton2': 'או צרו קשר דרך הטופס',
    'about.ctaNote': 'גם אם לא נעבוד יחד, תצא עם ראייה ברורה יותר.',

    // Services Page
    'servicesPage.badge': 'השירותים שלנו',
    'servicesPage.heroTitle1': 'פתרונות',
    'servicesPage.heroTitle2': 'אוטומציה מקצה לקצה',
    'servicesPage.heroSubtitle': 'מאבחון ראשוני ועד תחזוקה שוטפת - אנחנו כאן ללוות אתכם בכל שלב',
    'servicesPage.getQuote': 'קבלו הצעת מחיר',
    'servicesPage.includes': 'כולל:',
    'servicesPage.diagnosis.title': 'אבחון עסקי מקיף',
    'servicesPage.diagnosis.desc': 'נתחיל בהבנה מעמיקה של העסק שלכם. נזהה את התהליכים שגוזלים הכי הרבה זמן, את צווארי הבקבוק, ואת ההזדמנויות הכי גדולות לאוטומציה.',
    'servicesPage.diagnosis.f1': 'מיפוי תהליכים קיימים',
    'servicesPage.diagnosis.f2': 'זיהוי הזדמנויות לחיסכון',
    'servicesPage.diagnosis.f3': 'דוח מפורט עם המלצות',
    'servicesPage.diagnosis.f4': 'תוכנית פעולה מותאמת',
    'servicesPage.automation.title': 'אוטומציה עסקית',
    'servicesPage.automation.desc': 'נבנה עבורכם מערכות אוטומטיות שעובדות 24/7. מאוטומציה של תהליכי שיווק ומכירות, דרך ניהול מלאי ועד שירות לקוחות.',
    'servicesPage.automation.f1': 'אוטומציית שיווק ומכירות',
    'servicesPage.automation.f2': 'ניהול לידים אוטומטי',
    'servicesPage.automation.f3': 'אינטגרציות בין מערכות',
    'servicesPage.automation.f4': 'דוחות ותובנות בזמן אמת',
    'servicesPage.chatbots.title': 'צ\'אטבוטים חכמים',
    'servicesPage.chatbots.desc': 'בוטים מבוססי AI שמטפלים בלקוחות שלכם, עונים על שאלות, קובעים פגישות ומגדילים מכירות - הכל באופן אוטומטי.',
    'servicesPage.chatbots.f1': 'בוטים לוואטסאפ ופייסבוק',
    'servicesPage.chatbots.f2': 'מענה 24/7 ללקוחות',
    'servicesPage.chatbots.f3': 'קביעת פגישות אוטומטית',
    'servicesPage.chatbots.f4': 'אינטגרציה עם CRM',
    'servicesPage.web.title': 'פתרונות ווב מתקדמים',
    'servicesPage.web.desc': 'אתרים, מערכות ואפליקציות ווב שנבנות עם הטכנולוגיות המתקדמות ביותר. מהירות, אמינות, ותמיד מותאמות לצרכים שלכם.',
    'servicesPage.web.f1': 'אתרים עסקיים מותאמים',
    'servicesPage.web.f2': 'מערכות ניהול מותאמות',
    'servicesPage.web.f3': 'חנויות אונליין',
    'servicesPage.web.f4': 'אפליקציות ווב',
    'servicesPage.additionalTitle': 'שירותים נוספים',
    'servicesPage.additionalSubtitle': 'עוד פתרונות שיעזרו לעסק שלכם להתייעל',
    'servicesPage.integrations': 'אינטגרציות',
    'servicesPage.integrationsDesc': 'חיבור בין כל המערכות שלכם לעבודה חלקה',
    'servicesPage.dataManagement': 'ניהול נתונים',
    'servicesPage.dataManagementDesc': 'ארגון וניתוח נתונים לקבלת החלטות חכמות',
    'servicesPage.communicationAutomation': 'אוטומציית תקשורת',
    'servicesPage.communicationAutomationDesc': 'אימיילים, הודעות ותזכורות אוטומטיות',
    'servicesPage.reportsInsights': 'דוחות ותובנות',
    'servicesPage.reportsInsightsDesc': 'דשבורדים ודוחות בזמן אמת לכל התהליכים',
    'servicesPage.ctaTitle': 'לא בטוחים מאיפה להתחיל?',
    'servicesPage.ctaSubtitle': 'התחילו עם אבחון חינם. נבין יחד את הצרכים שלכם ונמליץ על הפתרונות המתאימים ביותר.',
    'servicesPage.ctaButton': 'קבלו אבחון חינם',

    // Pricing Page
    'pricingPage.badge': 'תמחור שקוף',
    'pricingPage.heroTitle1': 'חבילות',
    'pricingPage.heroTitle2': 'תמיכה ותחזוקה',
    'pricingPage.heroSubtitle': 'בחרו את החבילה שמתאימה לצרכים שלכם. ללא עלויות נסתרות.',
    'pricingPage.essential.desc': 'לעסקים קטנים שרוצים להתחיל עם תמיכה בסיסית',
    'pricingPage.business.desc': 'לעסקים בצמיחה שצריכים יותר תמיכה ויכולות',
    'pricingPage.vip.desc': 'לעסקים שדורשים את השירות המקיף ביותר',
    'pricingPage.feature.businessDays': 'תמיכה בימי עסקים',
    'pricingPage.feature.support6days': 'תמיכה 6 ימים בשבוע',
    'pricingPage.feature.weeklyOptimization': 'אופטימיזציה שבועית',
    'pricingPage.feature.unlimitedDev': 'פיתוחים מותאמים ללא הגבלה',
    'pricingPage.customTitle': 'צריכים משהו מותאם אישית?',
    'pricingPage.customSubtitle': 'אם אף אחת מהחבילות לא מתאימה לכם, נשמח לבנות חבילה מותאמת אישית לצרכים שלכם.',
    'pricingPage.customButton': 'בקשו הצעת מחיר מותאמת',
    'pricingPage.faqTitle': 'שאלות נפוצות',
    'pricingPage.faqSubtitle': 'תשובות לשאלות הכי נפוצות על החבילות שלנו',
    'pricingPage.faq1.q': 'מה כולל שעות התמיכה?',
    'pricingPage.faq1.a': 'שעות התמיכה כוללות כל עבודה על המערכות שלכם: תיקון באגים, עדכונים, שיפורים קטנים, וכל בקשה אחרת. שעות שלא נוצלו לא מועברות לחודש הבא.',
    'pricingPage.faq2.q': 'האם אפשר לשדרג או לשנמך חבילה?',
    'pricingPage.faq2.a': 'בהחלט! אפשר לשנות חבילה בכל חודש. השינוי ייכנס לתוקף מתחילת החודש הבא.',
    'pricingPage.faq3.q': 'מה קורה אם אני צריך יותר שעות?',
    'pricingPage.faq3.a': 'אפשר לרכוש שעות נוספות בנפרד, או לשדרג לחבילה גדולה יותר. נמליץ לכם על האופציה המשתלמת ביותר.',
    'pricingPage.faq4.q': 'האם יש התחייבות?',
    'pricingPage.faq4.a': 'אין התחייבות לתקופה מינימלית. אפשר לבטל בכל זמן עם התראה של 30 יום.',

    // Chatbot
    'chatbot.title': 'עוזר Zyflows',
    'chatbot.online': 'מחובר',
    'chatbot.welcome': 'שלום! איך אני יכול לעזור לכם?',
    'chatbot.placeholder': 'כתבו את ההודעה שלכם...',
    'chatbot.close': 'סגור צ\'אט',
    'chatbot.send': 'שלח',

    // Common UI
    'loading': 'טוען...',
    'closeMenu': 'סגור תפריט',
    'closeChat': "סגור צ'אט",
    'openChat': "פתח צ'אט",
    'openAccessibility': 'פתיחת תפריט נגישות',
    'closeAccessibility': 'סגור תפריט נגישות',

    // Accessibility Panel
    'panel.title': 'הגדרות נגישות',
    'panel.fontSize': 'גודל גופן',
    'panel.fontSize.normal': 'רגיל',
    'panel.fontSize.large': 'גדול',
    'panel.fontSize.extraLarge': 'גדול מאוד',
    'panel.contrast': 'ניגודיות צבעים',
    'panel.contrast.normal': 'רגיל',
    'panel.contrast.high': 'ניגודיות גבוהה',
    'panel.contrast.inverted': 'צבעים הפוכים',
    'panel.animations': 'אנימציות',
    'panel.reduceAnimations': 'הפחתת אנימציות',
    'panel.animationsHelp': 'הפעלת אפשרות זו תפחית את האנימציות באתר לשיפור הנגישות',
    'panel.reset': 'איפוס להגדרות ברירת מחדל',

    // Terms page
    'terms.badge': 'מסמכים משפטיים',
    'terms.title': 'תנאים',
    'terms.titleGradient': 'והגבלות',
    'terms.updated': 'עדכון אחרון: ינואר 2025',
    'terms.s1.title': '1. כללי',
    'terms.s2.title': '2. תיאור השירותים',
    'terms.s3.title': '3. תהליך העבודה',
    'terms.s4.title': '4. תנאי תשלום',
    'terms.s5.title': '5. מדיניות החזרים וביטולים',
    'terms.s6.title': '6. אחריות ותמיכה',
    'terms.s7.title': '7. שירותי ריטיינר',
    'terms.s8.title': '8. מערכות וכלים של צד שלישי',
    'terms.s9.title': '9. פרטיות וסודיות',
    'terms.s10.title': '10. קניין רוחני',
    'terms.s11.title': '11. הצגת תוצאות',
    'terms.s12.title': '12. שינויים בשירות',
    'terms.s13.title': '13. סיום התקשרות',
    'terms.s14.title': '14. סמכות שיפוט ודין חל',
    'terms.contactTitle': 'שאלות?',

    // Privacy page
    'privacy.badge': 'פרטיות',
    'privacy.title': 'מדיניות',
    'privacy.titleGradient': 'פרטיות',
    'privacy.updated': 'עדכון אחרון: ינואר 2025',
    'privacy.nav.title': 'ניווט מהיר',
    'privacy.nav.intro': 'מבוא',
    'privacy.nav.collection': 'איסוף מידע',
    'privacy.nav.usage': 'שימוש במידע',
    'privacy.nav.security': 'אבטחת מידע',
    'privacy.nav.thirdparty': 'כלים של צד שלישי',
    'privacy.nav.rights': 'זכויות הלקוח',
    'privacy.nav.retention': 'תקופות שמירה',
    'privacy.nav.ai': 'שיחות עם AI Agent',
    'privacy.nav.updates': 'עדכוני מדיניות',
    'privacy.nav.contact': 'יצירת קשר',
    'privacy.s1.title': '1. מבוא',
    'privacy.s2.title': '2. איסוף מידע',
    'privacy.s3.title': '3. שימוש במידע',
    'privacy.s4.title': '4. אבטחת מידע',
    'privacy.s5.title': '5. כלים של צד שלישי',
    'privacy.s6.title': '6. זכויות הלקוח',
    'privacy.s7.title': '7. תקופות שמירה',
    'privacy.s8.title': '8. שיחות עם AI Agent',
    'privacy.s9.title': '9. עדכוני מדיניות',
    'privacy.s10.title': '10. יצירת קשר',

    // Accessibility page
    'accessibility.badge': 'נגישות',
    'accessibility.title': 'הצהרת',
    'accessibility.titleGradient': 'נגישות',
    'accessibility.updated': 'עדכון אחרון: ינואר 2025',
    'accessibility.feature1.title': 'התאמות טקסט',
    'accessibility.feature2.title': 'צבעים וניגודיות',
    'accessibility.feature3.title': 'הדגשות חזותיות',
    'accessibility.feature4.title': 'ניווט מקלדת',
    'accessibility.feature5.title': 'תאימות קוראי מסך',
    'accessibility.s1.title': 'המחויבות שלנו לנגישות',
    'accessibility.s2.title': 'תקנים ועמידה בדרישות',
    'accessibility.s3.title': 'כלי הנגישות באתר',
    'accessibility.s4.title': 'כיצד להשתמש בכלי הנגישות',
    'accessibility.s5.title': 'מגבלות ידועות',
    'accessibility.s6.title': 'דפדפנים נתמכים',
    'accessibility.s7.title': 'נתקלתם בבעיית נגישות?',

    // Language
    'language': 'שפה',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.pricing': 'Tarifs',
    'nav.contact': 'Contact',
    'nav.cta': 'Consultation gratuite',

    // Hero Section
    'hero.badge': '🚀 La nouvelle génération de l\'automatisation',
    'hero.title1': 'Transformez votre entreprise avec',
    'hero.title2': 'l\'automatisation intelligente',
    'hero.subtitle': 'Arrêtez de perdre du temps. Nous construisons des systèmes qui fonctionnent 24/7, optimisent les processus et augmentent vos profits.',
    'hero.cta1': 'Diagnostic gratuit',
    'hero.cta2': 'Découvrez nos services',

    // SEO
    'meta.home.title': 'Zyflows | Solutions d\'Automatisation IA',
    'meta.home.description': 'Solutions d\'Automatisation IA & Lead Generation. Nous construisons des systèmes intelligents pour optimiser vos processus.',
    'meta.about.title': 'À propos de Zyflows | Experts en Automatisation',
    'meta.about.description': 'Découvrez Zyflows et son fondateur Raphaël. Experts en automatisation business et solutions digitales.',
    'meta.services.title': 'Nos Services | Zyflows',
    'meta.services.description': 'Automatisation, Chatbots, Solutions Web et plus. Découvrez comment nous pouvons transformer votre entreprise.',
    'meta.contact.title': 'Contact | Zyflows',
    'meta.contact.description': 'Prêt à passer à la vitesse supérieure ? Contactez-nous pour une consultation sur l\'automatisation de votre business.',
    'meta.pricing.title': 'Tarifs & Formules | Zyflows',
    'meta.pricing.description': 'Formules de support et maintenance pour entreprises. Choisissez la formule adaptée à vos besoins.',
    'meta.terms.title': 'Conditions d\'utilisation | Zyflows',
    'meta.terms.description': 'Conditions générales d\'utilisation de Zyflows. Lisez notre politique avant d\'utiliser nos services.',
    'meta.privacy.title': 'Politique de confidentialité | Zyflows',
    'meta.privacy.description': 'Politique de confidentialité de Zyflows. Nous nous engageons à protéger vos données personnelles.',
    'meta.accessibility.title': 'Déclaration d\'accessibilité | Zyflows',
    'meta.accessibility.description': 'Zyflows s\'engage à l\'accessibilité numérique complète pour tous les utilisateurs.',

    // Services Section (Index)
    'services.title': 'Solutions pour la croissance',
    'services.subtitle': 'Nous offrons une gamme de services pour aider votre entreprise à croître et s\'optimiser',
    'services.learnMore': 'En savoir plus',
    'services.diagnosis.title': 'Diagnostic business',
    'services.diagnosis.desc': 'Nous identifions les points les plus critiques à améliorer et automatiser dans votre entreprise.',
    'services.automation.title': 'Automatisation',
    'services.automation.desc': 'Nous construisons des systèmes qui fonctionnent 24/7 et remplacent le travail manuel.',
    'services.chatbots.title': 'Chatbots',
    'services.chatbots.desc': 'Des bots intelligents qui gèrent vos clients et augmentent les ventes.',
    'services.web.title': 'Solutions Web',
    'services.web.desc': 'Sites et systèmes web avancés pour votre entreprise.',

    // Process Section
    'process.title': 'Comment ça marche?',
    'process.subtitle': 'Un processus simple et efficace qui mène à des résultats exceptionnels',
    'process.step1.title': 'Diagnostic',
    'process.step1.desc': 'Nous analysons les processus existants et identifions les opportunités d\'amélioration.',
    'process.step2.title': 'Développement',
    'process.step2.desc': 'Nous développons et implémentons des solutions d\'automatisation personnalisées.',
    'process.step3.title': 'Croissance',
    'process.step3.desc': 'Nous étendons et améliorons selon les besoins évolutifs de l\'entreprise.',

    // Pricing Section
    'pricing.title': 'Forfaits support et maintenance',
    'pricing.subtitle': 'Choisissez le forfait adapté à vos besoins',
    'pricing.recommended': 'Recommandé',
    'pricing.mostPopular': 'Le plus populaire',
    'pricing.contactUs': 'Nous contacter',
    'pricing.essential.desc': 'Pour les petites entreprises qui débutent',
    'pricing.business.desc': 'Pour les entreprises en croissance',
    'pricing.vip.desc': 'Pour les entreprises exigeantes',
    'pricing.feature.support2h': '2 heures de support par mois',
    'pricing.feature.support6h': '6 heures de support par mois',
    'pricing.feature.support15h': '15 heures de support par mois',
    'pricing.feature.basicMaintenance': 'Maintenance de base',
    'pricing.feature.advancedMaintenance': 'Maintenance avancée',
    'pricing.feature.fullMaintenance': 'Maintenance complète',
    'pricing.feature.monthlyReport': 'Rapport mensuel',
    'pricing.feature.weeklyReports': 'Rapports hebdomadaires',
    'pricing.feature.dailyReports': 'Rapports quotidiens',
    'pricing.feature.response48h': 'Temps de réponse: 48h',
    'pricing.feature.response24h': 'Temps de réponse: 24h',
    'pricing.feature.response4h': 'Temps de réponse: 4h',
    'pricing.feature.monthlyOptimization': 'Optimisation mensuelle',
    'pricing.feature.premiumTools': 'Accès aux outils premium',
    'pricing.feature.dedicatedManager': 'Manager client dédié',
    'pricing.feature.customDev': 'Développements personnalisés',
    'pricing.feature.personalTraining': 'Formations personnelles',

    // Contact Section
    'contact.title': 'Parlons ensemble',
    'contact.subtitle': 'Des questions? Vous voulez savoir comment nous pouvons aider votre entreprise? Laissez vos coordonnées et nous vous recontacterons sous 24h.',
    'contact.whatsappDesc': 'Réponse rapide en quelques minutes',
    'contact.whatsappBtn': 'Contactez-nous sur WhatsApp',
    'contact.form.name': 'Nom complet',
    'contact.form.namePlaceholder': 'Entrez votre nom',
    'contact.form.phone': 'Téléphone',
    'contact.form.phonePlaceholder': '+33 6 00 00 00 00',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Parlez-nous de votre entreprise et comment nous pouvons vous aider...',
    'contact.form.submit': 'Envoyer',
    'contact.form.businessName': 'Nom de l\'entreprise',
    'contact.form.businessPlaceholder': 'Nom de votre société',
    'contact.form.subject': 'Comment pouvons-nous vous aider?',
    'contact.form.selectTopic': 'Choisissez un sujet',
    'contact.form.topicDiagnosis': 'Diagnostic business',
    'contact.form.topicAutomation': 'Automatisation',
    'contact.form.topicChatbot': 'Chatbot',
    'contact.form.topicWeb': 'Solutions web',
    'contact.form.topicSupport': 'Forfaits support',
    'contact.form.topicOther': 'Autre',
    'contact.form.responseTime': 'Nous vous répondrons sous 24h ouvrées',
    'contact.form.sendRequest': 'Envoyer la demande',

    // Contact Info
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.phoneIsrael': 'Israël',
    'contact.phoneFrance': 'France',
    'contact.offices': 'Bureaux',
    'contact.hours': 'Horaires',
    'contact.hoursValue': 'Dim-Jeu 09:00-18:00',
    'contact.location': 'Tel Aviv, Israël',
    'contact.whatsappTitle': 'Préférez WhatsApp?',
    'contact.whatsappQuick': 'Réponse rapide en quelques minutes',
    'contact.whatsappSend': 'Envoyer un message WhatsApp',
    'contact.talkToUs': 'Contactez-nous sur WhatsApp',
    'contact.ways': 'Moyens de contact',
    'contact.leaveDetails': 'Laissez vos coordonnées',
    'contact.heroTitle': 'Parlons',
    'contact.heroTitle2': 'ensemble',
    'contact.heroSubtitle': 'Des questions? Vous voulez savoir comment nous pouvons vous aider? Nous sommes là pour vous.',

    // Footer
    'footer.company': 'Entreprise',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'notFound.title': 'Page introuvable',
    'notFound.description': 'Désolé, la page que vous recherchez n\'existe pas. Le lien est peut-être incorrect ou la page a été supprimée.',
    'notFound.cta': 'Retour à l\'accueil',
    'footer.terms': 'CGU',
    'footer.privacy': 'Confidentialité',
    'footer.accessibility': 'Accessibilité',
    'footer.desc': 'Agence d\'automatisation leader spécialisée dans la création de systèmes intelligents pour les entreprises. Nous vous aidons à gagner du temps et à augmenter vos profits.',
    'footer.createdBy': 'Site créé par',
    'creator.title': 'Consultant IA & Développeur Web Full Stack',
    'creator.bio': 'Consultant en intelligence artificielle et développeur de solutions web complètes. J\'accompagne les entreprises dans l\'adoption de l\'IA et la création de systèmes digitaux performants.',
    'creator.contact': 'Me contacter',
    'creator.email': 'Email',
    'creator.phone': 'Téléphone',
    'creator.whatsapp': 'WhatsApp',
    'creator.linkedin': 'LinkedIn',

    // About Page
    'about.badge': 'À propos de Zyflows',
    'about.heroTitle': 'Transformer des processus complexes en systèmes simples, automatisés et fiables',
    'about.heroSubtitle': 'Zyflows accompagne les entreprises qui veulent arrêter de perdre du temps sur des tâches manuelles, mal organisées ou mal outillées.',
    'about.introTitle': 'Une introduction directe',
    'about.introText': 'Je m\'appelle Raphaël, fondateur de Zyflows. Je suis consultant en automatisation IA et en création de solutions digitales pour PME, indépendants et équipes opérationnelles. Mon travail consiste à structurer, automatiser et fiabiliser des processus métier avec des outils modernes, sans complexité inutile.',
    'about.whyTitle': 'Pourquoi j\'ai créé Zyflows',
    'about.whyProblem': 'J\'ai vu trop d\'entreprises utiliser des outils puissants de manière inefficace. Des logiciels empilés, des tâches répétitives faites à la main, des erreurs humaines évitables et une perte de temps constante.',
    'about.whyBackground': 'Avec mon parcours terrain, mêlant armée, cybersécurité, développement et automatisation, j\'ai compris une chose essentielle : un système doit être solide, clair et maîtrisable, sinon il devient un problème au lieu d\'une solution.',
    'about.whyConclusion': 'J\'ai créé Zyflows pour apporter cette structure. Pas pour vendre de la technologie, mais pour livrer des systèmes qui fonctionnent vraiment dans la réalité des entreprises.',
    'about.founderTitle': 'À propos du fondateur',
    'about.founderName': 'Raphaël',
    'about.founderRole': 'Consultant en automatisation IA | Fondateur de Zyflows',
    'about.founderLocation': 'Basé en Israël, je travaille avec des clients en France et en Israël',
    'about.founderLang': 'Français, Anglais, Hébreu',
    'about.pathTitle': 'Mon parcours',
    'about.path1': 'Service militaire - culture forte de la responsabilité, des procédures et du travail sous contrainte',
    'about.path2': 'Formation en cybersécurité - compréhension claire des enjeux de sécurité, de fiabilité et de gestion des risques',
    'about.path3': 'Développeur full stack - maîtrise du frontend et des logiques backend',
    'about.path4': 'Actuellement en 2ème année de licence en Business Management et Systèmes d\'Information',
    'about.path5': 'Spécialisation progressive dans l\'automatisation no-code, les agents IA et les workflows complexes',
    'about.deliverTitle': 'Ce que je livre',
    'about.deliver1': 'Automatisation de processus métier entiers',
    'about.deliver2': 'Suppression des tâches manuelles répétitives',
    'about.deliver3': 'Réduction drastique des erreurs humaines',
    'about.deliver4': 'Gains de 20 à 40 heures par mois pour les équipes opérationnelles',
    'about.positionNote': 'Je ne me positionne pas comme un simple exécutant technique. J\'aide mes clients à structurer leur fonctionnement, pas seulement à connecter des outils.',
    'about.methodTitle': 'Mon approche et ma philosophie',
    'about.methodIntro': 'Ma vision est simple : une bonne automatisation doit être compréhensible, fiable et maintenable, même sans moi.',
    'about.method1.title': 'Découverte',
    'about.method1.desc': 'Je commence par comprendre ton métier, tes contraintes et tes points de friction réels.',
    'about.method2.title': 'Design',
    'about.method2.desc': 'Je conçois une architecture logique, lisible et évolutive. Pas de bricolage opaque.',
    'about.method3.title': 'Implémentation',
    'about.method3.desc': 'Je construis les workflows, agents IA ou solutions web, avec tests et documentation.',
    'about.method4.title': 'Mesure',
    'about.method4.desc': 'Nous mesurons les gains concrets : temps, fiabilité, performance. Puis nous optimisons.',
    'about.methodConclusion': 'Ce qui différencie Zyflows, c\'est la responsabilité de bout en bout. Je ne livre pas des scénarios isolés. Je livre des systèmes exploitables.',
    'about.servicesTitle': 'Services et expertise',
    'about.servicesIntro': 'Zyflows intervient principalement sur trois axes.',
    'about.service1.title': 'Automatisation de workflows',
    'about.service1.desc': 'Création de workflows avancés avec n8n, Make et outils no-code.',
    'about.service1.result': 'Résultat typique : suppression de tâches manuelles et gains immédiats de temps.',
    'about.service2.title': 'Chatbots IA et agents intelligents',
    'about.service2.desc': 'Mise en place d\'agents capables de répondre, qualifier, planifier et déclencher des actions.',
    'about.service2.result': 'Résultat typique : meilleure réactivité client et réduction de la charge humaine.',
    'about.service3.title': 'Solutions web connectées',
    'about.service3.desc': 'Création de sites et outils web reliés à des systèmes d\'automatisation et d\'IA.',
    'about.service3.result': 'Résultat typique : parcours client fluide et process centralisés.',
    'about.testimonialsTitle': 'Ce que disent les clients',
    'about.testimonial1.text': '"Raphaël a structuré nos process de bout en bout. On a gagné un temps énorme et surtout de la fiabilité."',
    'about.testimonial1.author': 'Dirigeant, PME services',
    'about.testimonial2.text': '"Ce qui fait la différence, c\'est la clarté. Tout est expliqué, documenté et maîtrisé."',
    'about.testimonial2.author': 'Consultant indépendant',
    'about.testimonial3.text': '"L\'automatisation mise en place fonctionne vraiment au quotidien, sans dépendance."',
    'about.testimonial3.author': 'Fondateur, startup',
    'about.ctaTitle': 'Et maintenant ?',
    'about.ctaText': 'Si tu lis cette page, c\'est probablement que tu sais que tes processus peuvent être mieux structurés et automatisés.',
    'about.ctaProposition': 'Je te propose une chose simple : une discussion honnête, sans pression commerciale, pour voir si Zyflows est pertinent pour toi.',
    'about.ctaButton1': 'Réserver une consultation',
    'about.ctaButton2': 'Ou me contacter via le formulaire',
    'about.ctaNote': 'Même si on ne travaille pas ensemble, tu repartiras avec une vision plus claire.',

    // Services Page
    'servicesPage.badge': 'Nos services',
    'servicesPage.heroTitle1': 'Solutions',
    'servicesPage.heroTitle2': 'd\'automatisation de bout en bout',
    'servicesPage.heroSubtitle': 'Du diagnostic initial à la maintenance continue - nous sommes là pour vous accompagner à chaque étape',
    'servicesPage.getQuote': 'Demander un devis',
    'servicesPage.includes': 'Inclus:',
    'servicesPage.diagnosis.title': 'Diagnostic business complet',
    'servicesPage.diagnosis.desc': 'Nous commençons par une compréhension approfondie de votre entreprise. Nous identifions les processus les plus chronophages, les goulots d\'étranglement et les meilleures opportunités d\'automatisation.',
    'servicesPage.diagnosis.f1': 'Cartographie des processus existants',
    'servicesPage.diagnosis.f2': 'Identification des économies potentielles',
    'servicesPage.diagnosis.f3': 'Rapport détaillé avec recommandations',
    'servicesPage.diagnosis.f4': 'Plan d\'action personnalisé',
    'servicesPage.automation.title': 'Automatisation business',
    'servicesPage.automation.desc': 'Nous construisons des systèmes automatiques qui fonctionnent 24/7. De l\'automatisation marketing et ventes, à la gestion des stocks jusqu\'au service client.',
    'servicesPage.automation.f1': 'Automatisation marketing et ventes',
    'servicesPage.automation.f2': 'Gestion automatique des leads',
    'servicesPage.automation.f3': 'Intégrations inter-systèmes',
    'servicesPage.automation.f4': 'Rapports et insights en temps réel',
    'servicesPage.chatbots.title': 'Chatbots intelligents',
    'servicesPage.chatbots.desc': 'Des bots basés sur l\'IA qui gèrent vos clients, répondent aux questions, planifient des rendez-vous et augmentent les ventes - tout automatiquement.',
    'servicesPage.chatbots.f1': 'Bots pour WhatsApp et Facebook',
    'servicesPage.chatbots.f2': 'Réponse 24/7 aux clients',
    'servicesPage.chatbots.f3': 'Prise de rendez-vous automatique',
    'servicesPage.chatbots.f4': 'Intégration CRM',
    'servicesPage.web.title': 'Solutions web avancées',
    'servicesPage.web.desc': 'Sites, systèmes et applications web construits avec les technologies les plus avancées. Rapides, fiables, et toujours adaptés à vos besoins.',
    'servicesPage.web.f1': 'Sites business personnalisés',
    'servicesPage.web.f2': 'Systèmes de gestion sur mesure',
    'servicesPage.web.f3': 'Boutiques en ligne',
    'servicesPage.web.f4': 'Applications web',
    'servicesPage.additionalTitle': 'Services additionnels',
    'servicesPage.additionalSubtitle': 'D\'autres solutions pour optimiser votre entreprise',
    'servicesPage.integrations': 'Intégrations',
    'servicesPage.integrationsDesc': 'Connexion de tous vos systèmes pour un fonctionnement fluide',
    'servicesPage.dataManagement': 'Gestion des données',
    'servicesPage.dataManagementDesc': 'Organisation et analyse des données pour des décisions intelligentes',
    'servicesPage.communicationAutomation': 'Automatisation communication',
    'servicesPage.communicationAutomationDesc': 'Emails, messages et rappels automatiques',
    'servicesPage.reportsInsights': 'Rapports et insights',
    'servicesPage.reportsInsightsDesc': 'Tableaux de bord et rapports en temps réel pour tous les processus',
    'servicesPage.ctaTitle': 'Vous ne savez pas par où commencer?',
    'servicesPage.ctaSubtitle': 'Commencez par un diagnostic gratuit. Nous comprendrons ensemble vos besoins et vous recommanderons les meilleures solutions.',
    'servicesPage.ctaButton': 'Diagnostic gratuit',

    // Pricing Page
    'pricingPage.badge': 'Tarification transparente',
    'pricingPage.heroTitle1': 'Forfaits',
    'pricingPage.heroTitle2': 'support et maintenance',
    'pricingPage.heroSubtitle': 'Choisissez le forfait adapté à vos besoins. Sans frais cachés.',
    'pricingPage.essential.desc': 'Pour les petites entreprises qui débutent avec un support de base',
    'pricingPage.business.desc': 'Pour les entreprises en croissance qui ont besoin de plus de support',
    'pricingPage.vip.desc': 'Pour les entreprises qui exigent le service le plus complet',
    'pricingPage.feature.businessDays': 'Support jours ouvrés',
    'pricingPage.feature.support6days': 'Support 6 jours par semaine',
    'pricingPage.feature.weeklyOptimization': 'Optimisation hebdomadaire',
    'pricingPage.feature.unlimitedDev': 'Développements personnalisés illimités',
    'pricingPage.customTitle': 'Besoin d\'un forfait personnalisé?',
    'pricingPage.customSubtitle': 'Si aucun forfait ne vous convient, nous serons heureux de créer un forfait personnalisé selon vos besoins.',
    'pricingPage.customButton': 'Demander un devis personnalisé',
    'pricingPage.faqTitle': 'Questions fréquentes',
    'pricingPage.faqSubtitle': 'Réponses aux questions les plus fréquentes sur nos forfaits',
    'pricingPage.faq1.q': 'Que comprennent les heures de support?',
    'pricingPage.faq1.a': 'Les heures de support comprennent tout travail sur vos systèmes: correction de bugs, mises à jour, petites améliorations, et toute autre demande. Les heures non utilisées ne sont pas reportées au mois suivant.',
    'pricingPage.faq2.q': 'Peut-on upgrader ou downgrader le forfait?',
    'pricingPage.faq2.a': 'Absolument! Vous pouvez changer de forfait chaque mois. Le changement prendra effet au début du mois suivant.',
    'pricingPage.faq3.q': 'Que se passe-t-il si j\'ai besoin de plus d\'heures?',
    'pricingPage.faq3.a': 'Vous pouvez acheter des heures supplémentaires séparément, ou upgrader vers un forfait plus important. Nous vous recommanderons l\'option la plus avantageuse.',
    'pricingPage.faq4.q': 'Y a-t-il un engagement?',
    'pricingPage.faq4.a': 'Aucun engagement minimum. Vous pouvez annuler à tout moment avec un préavis de 30 jours.',

    // Chatbot
    'chatbot.title': 'Assistant ZyFlows',
    'chatbot.online': 'En ligne',
    'chatbot.welcome': 'Bonjour ! Comment puis-je vous aider ?',
    'chatbot.placeholder': 'Écrivez votre message...',
    'chatbot.close': 'Fermer le chat',
    'chatbot.send': 'Envoyer',

    // Common UI
    'loading': 'Chargement...',
    'closeMenu': 'Fermer le menu',
    'closeChat': 'Fermer le chat',
    'openChat': 'Ouvrir le chat',
    'openAccessibility': "Ouvrir les paramètres d'accessibilité",
    'closeAccessibility': "Fermer les paramètres d'accessibilité",

    // Accessibility Panel
    'panel.title': "Paramètres d'accessibilité",
    'panel.fontSize': 'Taille du texte',
    'panel.fontSize.normal': 'Normal',
    'panel.fontSize.large': 'Grand',
    'panel.fontSize.extraLarge': 'Très grand',
    'panel.contrast': 'Contraste des couleurs',
    'panel.contrast.normal': 'Normal',
    'panel.contrast.high': 'Contraste élevé',
    'panel.contrast.inverted': 'Couleurs inversées',
    'panel.animations': 'Animations',
    'panel.reduceAnimations': 'Réduire les animations',
    'panel.animationsHelp': "L'activation de cette option réduira les animations du site pour améliorer l'accessibilité",
    'panel.reset': 'Réinitialiser les paramètres',

    // Terms page
    'terms.badge': 'Documents juridiques',
    'terms.title': 'Conditions',
    'terms.titleGradient': "d'utilisation",
    'terms.updated': 'Dernière mise à jour : Janvier 2025',
    'terms.s1.title': '1. Généralités',
    'terms.s2.title': '2. Description des services',
    'terms.s3.title': '3. Processus de travail',
    'terms.s4.title': '4. Conditions de paiement',
    'terms.s5.title': '5. Politique de remboursement',
    'terms.s6.title': '6. Garantie et support',
    'terms.s7.title': '7. Services de retainer',
    'terms.s8.title': '8. Outils tiers',
    'terms.s9.title': '9. Confidentialité',
    'terms.s10.title': '10. Propriété intellectuelle',
    'terms.s11.title': '11. Présentation des résultats',
    'terms.s12.title': '12. Modifications du service',
    'terms.s13.title': '13. Résiliation',
    'terms.s14.title': '14. Juridiction applicable',
    'terms.contactTitle': 'Questions ?',

    // Privacy page
    'privacy.badge': 'Confidentialité',
    'privacy.title': 'Politique de',
    'privacy.titleGradient': 'confidentialité',
    'privacy.updated': 'Dernière mise à jour : Janvier 2025',
    'privacy.nav.title': 'Navigation rapide',
    'privacy.nav.intro': 'Introduction',
    'privacy.nav.collection': 'Collecte de données',
    'privacy.nav.usage': 'Utilisation des données',
    'privacy.nav.security': 'Sécurité des données',
    'privacy.nav.thirdparty': 'Outils tiers',
    'privacy.nav.rights': 'Droits du client',
    'privacy.nav.retention': 'Durées de conservation',
    'privacy.nav.ai': "Conversations avec l'IA",
    'privacy.nav.updates': 'Mises à jour de la politique',
    'privacy.nav.contact': 'Contact',
    'privacy.s1.title': '1. Introduction',
    'privacy.s2.title': '2. Collecte de données',
    'privacy.s3.title': '3. Utilisation des données',
    'privacy.s4.title': '4. Sécurité des données',
    'privacy.s5.title': '5. Outils tiers',
    'privacy.s6.title': '6. Droits du client',
    'privacy.s7.title': '7. Durées de conservation',
    'privacy.s8.title': "8. Conversations avec l'IA",
    'privacy.s9.title': '9. Mises à jour de la politique',
    'privacy.s10.title': '10. Contact',

    // Accessibility page
    'accessibility.badge': 'Accessibilité',
    'accessibility.title': "Déclaration d'",
    'accessibility.titleGradient': 'accessibilité',
    'accessibility.updated': 'Dernière mise à jour : Janvier 2025',
    'accessibility.feature1.title': 'Adaptations du texte',
    'accessibility.feature2.title': 'Couleurs et contraste',
    'accessibility.feature3.title': 'Mises en évidence visuelles',
    'accessibility.feature4.title': 'Navigation au clavier',
    'accessibility.feature5.title': "Compatibilité lecteurs d'écran",
    'accessibility.s1.title': "Notre engagement pour l'accessibilité",
    'accessibility.s2.title': 'Normes et conformité',
    'accessibility.s3.title': "Outils d'accessibilité",
    'accessibility.s4.title': 'Comment utiliser les outils',
    'accessibility.s5.title': 'Limitations connues',
    'accessibility.s6.title': 'Navigateurs supportés',
    'accessibility.s7.title': "Problème d'accessibilité ?",

    // Language
    'language': 'Langue',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.cta': 'Free Consultation',

    // Hero Section
    'hero.badge': '🚀 The next generation of business automation',
    'hero.title1': 'Transform your business with',
    'hero.title2': 'smart automation',
    'hero.subtitle': 'Stop wasting time. We build systems that work 24/7, streamline processes, and increase your profits.',
    'hero.cta1': 'Get a free diagnosis',
    'hero.cta2': 'Discover our services',

    // SEO
    'meta.home.title': 'Zyflows | AI Automation Solutions',
    'meta.home.description': 'AI Automation Solutions & Lead Generation. We build smart systems to streamline processes and boost growth.',
    'meta.about.title': 'About Zyflows | Automation Experts',
    'meta.about.description': 'Meet Zyflows and founder Raphaël. Experts in business automation and smart digital solutions.',
    'meta.services.title': 'Our Services | Zyflows',
    'meta.services.description': 'Automation, Chatbots, Web Solutions and more. Discover how we can upgrade your business.',
    'meta.contact.title': 'Contact Us | Zyflows',
    'meta.contact.description': 'Ready to move forward? Contact us for a consultation on business automation and development.',
    'meta.pricing.title': 'Pricing Plans | Zyflows',
    'meta.pricing.description': 'Support and maintenance plans for businesses. Choose the plan that fits your needs.',
    'meta.terms.title': 'Terms of Service | Zyflows',
    'meta.terms.description': 'Zyflows terms of service. Please read our policy before using our services.',
    'meta.privacy.title': 'Privacy Policy | Zyflows',
    'meta.privacy.description': 'Zyflows privacy policy. We are committed to protecting your personal data.',
    'meta.accessibility.title': 'Accessibility Statement | Zyflows',
    'meta.accessibility.description': 'Zyflows is committed to full digital accessibility for all users.',

    // Services Section (Index)
    'services.title': 'Solutions for business growth',
    'services.subtitle': 'We offer a range of services to help your business grow and optimize',
    'services.learnMore': 'Learn more',
    'services.diagnosis.title': 'Business Diagnosis',
    'services.diagnosis.desc': 'We identify the most critical points for improvement and automation in your business.',
    'services.automation.title': 'Automation',
    'services.automation.desc': 'We build systems that work 24/7 and replace manual work.',
    'services.chatbots.title': 'Chatbots',
    'services.chatbots.desc': 'Smart bots that handle customers and increase sales.',
    'services.web.title': 'Web Solutions',
    'services.web.desc': 'Advanced websites and web systems for your business.',

    // Process Section
    'process.title': 'How does it work?',
    'process.subtitle': 'A simple and efficient process that leads to amazing results',
    'process.step1.title': 'Diagnosis',
    'process.step1.desc': 'We analyze existing processes and identify improvement opportunities.',
    'process.step2.title': 'Build',
    'process.step2.desc': 'We develop and implement customized automation solutions.',
    'process.step3.title': 'Growth',
    'process.step3.desc': 'We expand and improve according to the evolving business needs.',

    // Pricing Section
    'pricing.title': 'Support & Maintenance Packages',
    'pricing.subtitle': 'Choose the package that fits your needs',
    'pricing.recommended': 'Recommended',
    'pricing.mostPopular': 'Most Popular',
    'pricing.contactUs': 'Contact Us',
    'pricing.essential.desc': 'For small businesses getting started',
    'pricing.business.desc': 'For growing businesses that need more',
    'pricing.vip.desc': 'For businesses that demand the maximum',
    'pricing.feature.support2h': '2 hours support per month',
    'pricing.feature.support6h': '6 hours support per month',
    'pricing.feature.support15h': '15 hours support per month',
    'pricing.feature.basicMaintenance': 'Basic maintenance',
    'pricing.feature.advancedMaintenance': 'Advanced maintenance',
    'pricing.feature.fullMaintenance': 'Full maintenance',
    'pricing.feature.monthlyReport': 'Monthly report',
    'pricing.feature.weeklyReports': 'Weekly reports',
    'pricing.feature.dailyReports': 'Daily reports',
    'pricing.feature.response48h': 'Response time: 48 hours',
    'pricing.feature.response24h': 'Response time: 24 hours',
    'pricing.feature.response4h': 'Response time: 4 hours',
    'pricing.feature.monthlyOptimization': 'Monthly optimization',
    'pricing.feature.premiumTools': 'Access to premium tools',
    'pricing.feature.dedicatedManager': 'Dedicated account manager',
    'pricing.feature.customDev': 'Custom development',
    'pricing.feature.personalTraining': 'Personal training',

    // Contact Section
    'contact.title': 'Let\'s Talk',
    'contact.subtitle': 'Have questions? Want to know how we can help your business? Leave your details and we\'ll get back to you within 24 hours.',
    'contact.whatsappDesc': 'Quick response within minutes',
    'contact.whatsappBtn': 'Chat with us on WhatsApp',
    'contact.form.name': 'Full Name',
    'contact.form.namePlaceholder': 'Enter your name',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+1 (555) 000-0000',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us about your business and how we can help...',
    'contact.form.submit': 'Send Message',
    'contact.form.businessName': 'Business Name',
    'contact.form.businessPlaceholder': 'Your company name',
    'contact.form.subject': 'How can we help?',
    'contact.form.selectTopic': 'Select a topic',
    'contact.form.topicDiagnosis': 'Business diagnosis',
    'contact.form.topicAutomation': 'Automation',
    'contact.form.topicChatbot': 'Chatbot',
    'contact.form.topicWeb': 'Web solutions',
    'contact.form.topicSupport': 'Support packages',
    'contact.form.topicOther': 'Other',
    'contact.form.responseTime': 'We\'ll respond within 24 business hours',
    'contact.form.sendRequest': 'Send Request',

    // Contact Info
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.phoneIsrael': 'Israel',
    'contact.phoneFrance': 'France',
    'contact.offices': 'Offices',
    'contact.hours': 'Working Hours',
    'contact.hoursValue': 'Sun-Thu 09:00-18:00',
    'contact.location': 'Tel Aviv, Israel',
    'contact.whatsappTitle': 'Prefer WhatsApp?',
    'contact.whatsappQuick': 'Get a quick response within minutes',
    'contact.whatsappSend': 'Send WhatsApp message',
    'contact.talkToUs': 'Chat with us on WhatsApp',
    'contact.ways': 'Contact Methods',
    'contact.leaveDetails': 'Leave your details',
    'contact.heroTitle': 'Let\'s',
    'contact.heroTitle2': 'Talk',
    'contact.heroSubtitle': 'Have questions? Want to know how we can help? We\'re here for you.',

    // Footer
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'notFound.title': 'Page not found',
    'notFound.description': 'Sorry, the page you are looking for does not exist. The link may be incorrect or the page has been removed.',
    'notFound.cta': 'Back to home',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.accessibility': 'Accessibility',
    'footer.desc': 'Leading automation agency specializing in building smart systems for businesses. We help you save time and increase profits.',
    'footer.createdBy': 'Website created by',
    'creator.title': 'AI Consultant & Full Stack Web Developer',
    'creator.bio': 'AI consultant and full stack web developer. I help businesses adopt AI technologies and build complete digital solutions that work.',
    'creator.contact': 'Contact me',
    'creator.email': 'Email',
    'creator.phone': 'Phone',
    'creator.whatsapp': 'WhatsApp',
    'creator.linkedin': 'LinkedIn',

    // About Page
    'about.badge': 'About Zyflows',
    'about.heroTitle': 'Transforming complex processes into simple, automated and reliable systems',
    'about.heroSubtitle': 'Zyflows helps businesses that want to stop wasting time on manual, disorganized or poorly-tooled tasks.',
    'about.introTitle': 'A direct introduction',
    'about.introText': 'My name is Raphaël, founder of Zyflows. I\'m a consultant in AI automation and digital solutions for SMBs, freelancers and operational teams. My work is to structure, automate and make business processes reliable with modern tools, without unnecessary complexity.',
    'about.whyTitle': 'Why I created Zyflows',
    'about.whyProblem': 'I\'ve seen too many businesses use powerful tools inefficiently. Stacked software, repetitive manual tasks, avoidable human errors and constant time waste.',
    'about.whyBackground': 'With my field experience combining army, cybersecurity, development and automation, I understood one essential thing: a system must be solid, clear and controllable, otherwise it becomes a problem instead of a solution.',
    'about.whyConclusion': 'I created Zyflows to bring this structure. Not to sell technology, but to deliver systems that actually work in business reality.',
    'about.founderTitle': 'About the founder',
    'about.founderName': 'Raphaël',
    'about.founderRole': 'AI Automation Consultant | Founder of Zyflows',
    'about.founderLocation': 'Based in Israel, working with clients in France and Israel',
    'about.founderLang': 'French, English, Hebrew',
    'about.pathTitle': 'My background',
    'about.path1': 'Military service - strong culture of responsibility, procedures and work under pressure',
    'about.path2': 'Cybersecurity training - clear understanding of security, reliability and risk management',
    'about.path3': 'Full stack developer - mastering frontend and backend logic',
    'about.path4': 'Currently in 2nd year of Bachelor\'s degree in Business Management and Information Systems',
    'about.path5': 'Progressive specialization in no-code automation, AI agents and complex workflows',
    'about.deliverTitle': 'What I deliver',
    'about.deliver1': 'Automation of entire business processes',
    'about.deliver2': 'Elimination of repetitive manual tasks',
    'about.deliver3': 'Drastic reduction of human errors',
    'about.deliver4': 'Savings of 20-40 hours per month for operational teams',
    'about.positionNote': 'I don\'t position myself as a simple technical executor. I help my clients structure their operations, not just connect tools.',
    'about.methodTitle': 'My approach and philosophy',
    'about.methodIntro': 'My vision is simple: good automation must be understandable, reliable and maintainable, even without me.',
    'about.method1.title': 'Discovery',
    'about.method1.desc': 'I start by understanding your business, your constraints and your real friction points.',
    'about.method2.title': 'Design',
    'about.method2.desc': 'I design a logical, readable and scalable architecture. No opaque workarounds.',
    'about.method3.title': 'Implementation',
    'about.method3.desc': 'I build the workflows, AI agents or web solutions, with tests and documentation.',
    'about.method4.title': 'Measurement',
    'about.method4.desc': 'We measure concrete gains: time, reliability, performance. Then we optimize.',
    'about.methodConclusion': 'What differentiates Zyflows is end-to-end responsibility. I don\'t deliver isolated scenarios. I deliver systems you can operate.',
    'about.servicesTitle': 'Services and expertise',
    'about.servicesIntro': 'Zyflows works mainly on three axes.',
    'about.service1.title': 'Workflow automation',
    'about.service1.desc': 'Creation of advanced workflows with n8n, Make and no-code tools.',
    'about.service1.result': 'Typical result: elimination of manual tasks and immediate time savings.',
    'about.service2.title': 'AI chatbots and smart agents',
    'about.service2.desc': 'Implementation of agents capable of responding, qualifying, scheduling and triggering actions.',
    'about.service2.result': 'Typical result: better client responsiveness and reduced human workload.',
    'about.service3.title': 'Connected web solutions',
    'about.service3.desc': 'Creation of websites and web tools connected to automation and AI systems.',
    'about.service3.result': 'Typical result: smooth customer journey and centralized processes.',
    'about.testimonialsTitle': 'What clients say',
    'about.testimonial1.text': '"Raphaël structured our processes end to end. We saved enormous time and especially gained reliability."',
    'about.testimonial1.author': 'Director, Services SMB',
    'about.testimonial2.text': '"What makes the difference is clarity. Everything is explained, documented and controlled."',
    'about.testimonial2.author': 'Independent consultant',
    'about.testimonial3.text': '"The automation implemented really works daily, without dependency."',
    'about.testimonial3.author': 'Founder, startup',
    'about.ctaTitle': 'What now?',
    'about.ctaText': 'If you\'re reading this page, you probably know that your processes could be better structured and automated.',
    'about.ctaProposition': 'I offer you something simple: an honest discussion, without sales pressure, to see if Zyflows is relevant for you.',
    'about.ctaButton1': 'Book a consultation',
    'about.ctaButton2': 'Or contact me via the form',
    'about.ctaNote': 'Even if we don\'t work together, you\'ll leave with a clearer vision.',

    // Services Page
    'servicesPage.badge': 'Our Services',
    'servicesPage.heroTitle1': 'End-to-end',
    'servicesPage.heroTitle2': 'automation solutions',
    'servicesPage.heroSubtitle': 'From initial diagnosis to ongoing maintenance - we\'re here to support you every step',
    'servicesPage.getQuote': 'Get a quote',
    'servicesPage.includes': 'Includes:',
    'servicesPage.diagnosis.title': 'Comprehensive Business Diagnosis',
    'servicesPage.diagnosis.desc': 'We start with a deep understanding of your business. We identify the most time-consuming processes, bottlenecks, and the biggest automation opportunities.',
    'servicesPage.diagnosis.f1': 'Mapping existing processes',
    'servicesPage.diagnosis.f2': 'Identifying savings opportunities',
    'servicesPage.diagnosis.f3': 'Detailed report with recommendations',
    'servicesPage.diagnosis.f4': 'Customized action plan',
    'servicesPage.automation.title': 'Business Automation',
    'servicesPage.automation.desc': 'We build automated systems that work 24/7. From marketing and sales automation, to inventory management and customer service.',
    'servicesPage.automation.f1': 'Marketing and sales automation',
    'servicesPage.automation.f2': 'Automatic lead management',
    'servicesPage.automation.f3': 'System integrations',
    'servicesPage.automation.f4': 'Real-time reports and insights',
    'servicesPage.chatbots.title': 'Smart Chatbots',
    'servicesPage.chatbots.desc': 'AI-powered bots that handle your customers, answer questions, schedule appointments and increase sales - all automatically.',
    'servicesPage.chatbots.f1': 'Bots for WhatsApp and Facebook',
    'servicesPage.chatbots.f2': '24/7 customer response',
    'servicesPage.chatbots.f3': 'Automatic appointment scheduling',
    'servicesPage.chatbots.f4': 'CRM integration',
    'servicesPage.web.title': 'Advanced Web Solutions',
    'servicesPage.web.desc': 'Websites, systems and web applications built with the most advanced technologies. Fast, reliable, and always tailored to your needs.',
    'servicesPage.web.f1': 'Custom business websites',
    'servicesPage.web.f2': 'Custom management systems',
    'servicesPage.web.f3': 'Online stores',
    'servicesPage.web.f4': 'Web applications',
    'servicesPage.additionalTitle': 'Additional Services',
    'servicesPage.additionalSubtitle': 'More solutions to help your business optimize',
    'servicesPage.integrations': 'Integrations',
    'servicesPage.integrationsDesc': 'Connecting all your systems for seamless operation',
    'servicesPage.dataManagement': 'Data Management',
    'servicesPage.dataManagementDesc': 'Organizing and analyzing data for smart decisions',
    'servicesPage.communicationAutomation': 'Communication Automation',
    'servicesPage.communicationAutomationDesc': 'Automatic emails, messages and reminders',
    'servicesPage.reportsInsights': 'Reports & Insights',
    'servicesPage.reportsInsightsDesc': 'Real-time dashboards and reports for all processes',
    'servicesPage.ctaTitle': 'Not sure where to start?',
    'servicesPage.ctaSubtitle': 'Start with a free diagnosis. We\'ll understand your needs together and recommend the best solutions.',
    'servicesPage.ctaButton': 'Get a free diagnosis',

    // Pricing Page
    'pricingPage.badge': 'Transparent Pricing',
    'pricingPage.heroTitle1': 'Support &',
    'pricingPage.heroTitle2': 'Maintenance Packages',
    'pricingPage.heroSubtitle': 'Choose the package that fits your needs. No hidden costs.',
    'pricingPage.essential.desc': 'For small businesses starting with basic support',
    'pricingPage.business.desc': 'For growing businesses that need more support and capabilities',
    'pricingPage.vip.desc': 'For businesses that demand the most comprehensive service',
    'pricingPage.feature.businessDays': 'Business days support',
    'pricingPage.feature.support6days': '6 days a week support',
    'pricingPage.feature.weeklyOptimization': 'Weekly optimization',
    'pricingPage.feature.unlimitedDev': 'Unlimited custom development',
    'pricingPage.customTitle': 'Need something custom?',
    'pricingPage.customSubtitle': 'If none of the packages fit you, we\'ll be happy to build a custom package for your needs.',
    'pricingPage.customButton': 'Request a custom quote',
    'pricingPage.faqTitle': 'Frequently Asked Questions',
    'pricingPage.faqSubtitle': 'Answers to the most common questions about our packages',
    'pricingPage.faq1.q': 'What do support hours include?',
    'pricingPage.faq1.a': 'Support hours include all work on your systems: bug fixes, updates, small improvements, and any other request. Unused hours do not carry over to the next month.',
    'pricingPage.faq2.q': 'Can I upgrade or downgrade my package?',
    'pricingPage.faq2.a': 'Absolutely! You can change packages every month. The change will take effect at the beginning of the next month.',
    'pricingPage.faq3.q': 'What if I need more hours?',
    'pricingPage.faq3.a': 'You can purchase additional hours separately, or upgrade to a larger package. We\'ll recommend the most cost-effective option for you.',
    'pricingPage.faq4.q': 'Is there a commitment?',
    'pricingPage.faq4.a': 'No minimum commitment. You can cancel at any time with 30 days notice.',

    // Chatbot
    'chatbot.title': 'ZyFlows Assistant',
    'chatbot.online': 'Online',
    'chatbot.welcome': 'Hello! How can I help you?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.close': 'Close chat',
    'chatbot.send': 'Send',

    // Common UI
    'loading': 'Loading...',
    'closeMenu': 'Close menu',
    'closeChat': 'Close chat',
    'openChat': 'Open chat',
    'openAccessibility': 'Open accessibility settings',
    'closeAccessibility': 'Close accessibility settings',

    // Accessibility Panel
    'panel.title': 'Accessibility settings',
    'panel.fontSize': 'Font size',
    'panel.fontSize.normal': 'Normal',
    'panel.fontSize.large': 'Large',
    'panel.fontSize.extraLarge': 'Extra large',
    'panel.contrast': 'Color contrast',
    'panel.contrast.normal': 'Normal',
    'panel.contrast.high': 'High contrast',
    'panel.contrast.inverted': 'Inverted colors',
    'panel.animations': 'Animations',
    'panel.reduceAnimations': 'Reduce animations',
    'panel.animationsHelp': 'Enabling this option will reduce site animations to improve accessibility',
    'panel.reset': 'Reset to default settings',

    // Terms page
    'terms.badge': 'Legal Documents',
    'terms.title': 'Terms',
    'terms.titleGradient': '& Conditions',
    'terms.updated': 'Last updated: January 2025',
    'terms.s1.title': '1. General',
    'terms.s2.title': '2. Service Description',
    'terms.s3.title': '3. Work Process',
    'terms.s4.title': '4. Payment Terms',
    'terms.s5.title': '5. Refund Policy',
    'terms.s6.title': '6. Warranty & Support',
    'terms.s7.title': '7. Retainer Services',
    'terms.s8.title': '8. Third-Party Tools',
    'terms.s9.title': '9. Privacy & Confidentiality',
    'terms.s10.title': '10. Intellectual Property',
    'terms.s11.title': '11. Results Disclosure',
    'terms.s12.title': '12. Service Changes',
    'terms.s13.title': '13. Termination',
    'terms.s14.title': '14. Governing Law',
    'terms.contactTitle': 'Questions?',

    // Privacy page
    'privacy.badge': 'Privacy',
    'privacy.title': 'Privacy',
    'privacy.titleGradient': 'Policy',
    'privacy.updated': 'Last updated: January 2025',
    'privacy.nav.title': 'Quick Navigation',
    'privacy.nav.intro': 'Introduction',
    'privacy.nav.collection': 'Data Collection',
    'privacy.nav.usage': 'Data Usage',
    'privacy.nav.security': 'Data Security',
    'privacy.nav.thirdparty': 'Third-Party Tools',
    'privacy.nav.rights': 'Client Rights',
    'privacy.nav.retention': 'Retention Periods',
    'privacy.nav.ai': 'AI Agent Conversations',
    'privacy.nav.updates': 'Policy Updates',
    'privacy.nav.contact': 'Contact',
    'privacy.s1.title': '1. Introduction',
    'privacy.s2.title': '2. Data Collection',
    'privacy.s3.title': '3. Data Usage',
    'privacy.s4.title': '4. Data Security',
    'privacy.s5.title': '5. Third-Party Tools',
    'privacy.s6.title': '6. Client Rights',
    'privacy.s7.title': '7. Retention Periods',
    'privacy.s8.title': '8. AI Agent Conversations',
    'privacy.s9.title': '9. Policy Updates',
    'privacy.s10.title': '10. Contact',

    // Accessibility page
    'accessibility.badge': 'Accessibility',
    'accessibility.title': 'Accessibility',
    'accessibility.titleGradient': 'Statement',
    'accessibility.updated': 'Last updated: January 2025',
    'accessibility.feature1.title': 'Text Adaptations',
    'accessibility.feature2.title': 'Colors & Contrast',
    'accessibility.feature3.title': 'Visual Highlights',
    'accessibility.feature4.title': 'Keyboard Navigation',
    'accessibility.feature5.title': 'Screen Reader Compatibility',
    'accessibility.s1.title': 'Our Commitment to Accessibility',
    'accessibility.s2.title': 'Standards & Compliance',
    'accessibility.s3.title': 'Accessibility Tools',
    'accessibility.s4.title': 'How to Use the Tools',
    'accessibility.s5.title': 'Known Limitations',
    'accessibility.s6.title': 'Supported Browsers',
    'accessibility.s7.title': 'Found an Accessibility Issue?',

    // Language
    'language': 'Language',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const navigate = useNavigate();
  const location = useLocation();

  // Initialize language from URL or localStorage or default
  const [language, setLanguageState] = useState<Language>(() => {
    // Check URL first
    const pathSegments = window.location.pathname.split('/').filter(Boolean);
    const firstSegment = pathSegments[0] as Language;
    if (['he', 'fr', 'en'].includes(firstSegment)) {
      return firstSegment;
    }

    // Fallback to localStorage
    const saved = localStorage.getItem('zyflows-language');
    if (saved && ['he', 'fr', 'en'].includes(saved)) {
      return saved as Language;
    }

    return 'he';
  });

  // Sync state with URL changes
  useEffect(() => {
    const pathSegments = location.pathname.split('/').filter(Boolean);
    const urlLang = pathSegments[0] as Language;

    if (['he', 'fr', 'en'].includes(urlLang) && urlLang !== language) {
      setLanguageState(urlLang);
    }
  }, [location.pathname]);

  // Update URL when language changes via setLanguage
  const setLanguage = (lang: Language) => {
    if (lang === language) return;

    setLanguageState(lang);
    localStorage.setItem('zyflows-language', lang);

    // Update URL: replace the language segment
    const currentPath = location.pathname;
    // Remove existing lang prefix if present
    const cleanPath = currentPath.replace(/^\/(he|fr|en)/, '');
    // Ensure cleanPath starts with / if it's not empty, or is just /
    const normalizedPath = cleanPath.startsWith('/') ? cleanPath : `/${cleanPath}`;

    // New path - handle root case carefully
    const newPath = `/${lang}${normalizedPath === '/' ? '' : normalizedPath}`;

    navigate(newPath);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  const dir = language === 'he' ? 'rtl' : 'ltr';

  useEffect(() => {
    updateDocumentDirection(language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
